language: node_js
node_js:
- '10'
dist: trusty
before_script:
- yarn install
script:
- yarn lint
- yarn build
cache:
  directories:
  - node_modules
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: dist
    github_token: $GITHUB_TOKEN
    target_branch: gh-pages
    fqdn: http://commit-comp.bbody.io
    repo: bbody/commit-comp
    on:
      branch: master