language: node_js
node_js:
- 10
dist: trusty
install:
  # - cypress install
  - yarn install
script:
  - yarn lint
  - yarn test:unit
  - yarn test:e2e
  - yarn build
cache:
  npm: true
  directories:
  - ~/.cache
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: dist
    github_token: $GITHUB_TOKEN
    target_branch: gh-pages
    fqdn: http://commit-comp.bbody.io
    repo: bbody/commit-comp
    on:
      branch: master
after_script:
  - cat ./coverage/lcov.info | coveralls