language: node_js
os:
  - linux
node_js:
- 10
dist: trusty
install:
  # - cypress install
  - yarn install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - yarn lint
  - yarn test:unit
  - yarn test:e2e -- --headless
  - yarn build
cache:
  npm: true
  directories:
  - ~/.cache
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: dist
    github_token: $GITHUB_TOKEN
    target_branch: gh-pages
    fqdn: http://commit-comp.bbody.io
    repo: bbody/commit-comp
    on:
      branch: master
after_script:
  - cat ./coverage/lcov.info | coveralls